[2024-05-09T19:18:44.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T19:18:44.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-05-09T19:18:44.159+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-05-09T19:18:44.246+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T19:18:44.468+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): Notificar_Equipo> on 2024-03-01 00:00:00+00:00
[2024-05-09T19:18:44.476+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=558) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T19:18:44.478+0000] {standard_task_runner.py:63} INFO - Started process 560 to run task
[2024-05-09T19:18:44.477+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX', 'Notificar_Equipo', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '947', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX.py', '--cfg-path', '/tmp/tmp2lta67jy']
[2024-05-09T19:18:44.479+0000] {standard_task_runner.py:91} INFO - Job 947: Subtask Notificar_Equipo
[2024-05-09T19:18:44.601+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-03-01T00:00:00+00:00 [running]> on host 7a81a983afb0
[2024-05-09T19:18:44.908+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX' AIRFLOW_CTX_TASK_ID='Notificar_Equipo' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-05-09T19:18:44.909+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T19:18:44.926+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-09T19:18:44.928+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-09T19:18:44.928+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-09T19:18:44.929+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T19:18:44.930+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-05-09T19:18:44.938+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Proyecto_SpaceX, task_id=Notificar_Equipo, run_id=scheduled__2024-03-01T00:00:00+00:00, execution_date=20240301T000000, start_date=20240509T191844, end_date=20240509T191844
[2024-05-09T19:18:45.083+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 947 for task Notificar_Equipo ([Errno 99] Cannot assign requested address; 560)
[2024-05-09T19:18:45.096+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T19:18:45.111+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T19:18:45.204+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T21:02:01.679+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T21:02:01.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-05-09T21:02:01.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-05-09T21:02:01.712+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T21:02:01.852+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): Notificar_Equipo> on 2024-03-01 00:00:00+00:00
[2024-05-09T21:02:01.859+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1901) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T21:02:01.861+0000] {standard_task_runner.py:63} INFO - Started process 1903 to run task
[2024-05-09T21:02:01.860+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX', 'Notificar_Equipo', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '1019', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX.py', '--cfg-path', '/tmp/tmppt5as6ew']
[2024-05-09T21:02:01.863+0000] {standard_task_runner.py:91} INFO - Job 1019: Subtask Notificar_Equipo
[2024-05-09T21:02:01.913+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX.Notificar_Equipo scheduled__2024-03-01T00:00:00+00:00 [running]> on host 7a81a983afb0
[2024-05-09T21:02:01.997+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX' AIRFLOW_CTX_TASK_ID='Notificar_Equipo' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-05-09T21:02:01.999+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T21:02:02.023+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-09T21:02:02.024+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-09T21:02:02.025+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-09T21:02:02.026+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T21:02:02.028+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-05-09T21:02:02.037+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Proyecto_SpaceX, task_id=Notificar_Equipo, run_id=scheduled__2024-03-01T00:00:00+00:00, execution_date=20240301T000000, start_date=20240509T210201, end_date=20240509T210202
[2024-05-09T21:02:02.051+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1019 for task Notificar_Equipo ([Errno 99] Cannot assign requested address; 1903)
[2024-05-09T21:02:02.076+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T21:02:02.091+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T21:02:02.094+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
