[2024-05-10T06:11:53.825+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T06:11:53.842+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-02T00:00:00+00:00 [queued]>
[2024-05-10T06:11:53.849+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-02T00:00:00+00:00 [queued]>
[2024-05-10T06:11:53.851+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-10T06:11:53.862+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Enviar_Mensaje> on 2024-03-02 00:00:00+00:00
[2024-05-10T06:11:53.869+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1343) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T06:11:53.870+0000] {standard_task_runner.py:63} INFO - Started process 1345 to run task
[2024-05-10T06:11:53.870+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX_v1', 'Enviar_Mensaje', 'scheduled__2024-03-02T00:00:00+00:00', '--job-id', '1153', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX_v1.py', '--cfg-path', '/tmp/tmp2a_w75sm']
[2024-05-10T06:11:53.871+0000] {standard_task_runner.py:91} INFO - Job 1153: Subtask Enviar_Mensaje
[2024-05-10T06:11:53.908+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-02T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T06:11:54.098+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX_v1' AIRFLOW_CTX_TASK_ID='Enviar_Mensaje' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-02T00:00:00+00:00'
[2024-05-10T06:11:54.099+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T06:11:54.106+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-10T06:11:54.108+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo '2024-03-02: Los datos fueron cargados'"]
[2024-05-10T06:11:54.116+0000] {subprocess.py:86} INFO - Output:
[2024-05-10T06:11:54.117+0000] {subprocess.py:93} INFO - 2024-03-02: Los datos fueron cargados
[2024-05-10T06:11:54.118+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-10T06:11:54.119+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T06:11:54.139+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Proyecto_SpaceX_v1, task_id=Enviar_Mensaje, run_id=scheduled__2024-03-02T00:00:00+00:00, execution_date=20240302T000000, start_date=20240510T061153, end_date=20240510T061154
[2024-05-10T06:11:54.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T06:11:54.180+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T06:11:54.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
