[2024-05-10T06:17:05.158+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T06:17:05.175+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-05-10T06:17:05.182+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-05-10T06:17:05.183+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-10T06:17:05.194+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Enviar_Mensaje> on 2024-03-12 00:00:00+00:00
[2024-05-10T06:17:05.201+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1676) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T06:17:05.203+0000] {standard_task_runner.py:63} INFO - Started process 1678 to run task
[2024-05-10T06:17:05.203+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX_v1', 'Enviar_Mensaje', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '1216', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX_v1.py', '--cfg-path', '/tmp/tmp18gw9jgb']
[2024-05-10T06:17:05.205+0000] {standard_task_runner.py:91} INFO - Job 1216: Subtask Enviar_Mensaje
[2024-05-10T06:17:05.247+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-12T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T06:17:05.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX_v1' AIRFLOW_CTX_TASK_ID='Enviar_Mensaje' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-05-10T06:17:05.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T06:17:05.460+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-10T06:17:05.461+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo '2024-03-12: Los datos fueron cargados'"]
[2024-05-10T06:17:05.470+0000] {subprocess.py:86} INFO - Output:
[2024-05-10T06:17:05.471+0000] {subprocess.py:93} INFO - 2024-03-12: Los datos fueron cargados
[2024-05-10T06:17:05.472+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-10T06:17:05.474+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T06:17:05.494+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Proyecto_SpaceX_v1, task_id=Enviar_Mensaje, run_id=scheduled__2024-03-12T00:00:00+00:00, execution_date=20240312T000000, start_date=20240510T061705, end_date=20240510T061705
[2024-05-10T06:17:05.539+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T06:17:05.554+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T06:17:05.565+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
