[2024-05-10T06:22:28.677+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T06:22:28.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-05-10T06:22:28.813+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-05-10T06:22:28.816+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-10T06:22:28.827+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Enviar_Mensaje> on 2024-03-22 00:00:00+00:00
[2024-05-10T06:22:28.834+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2031) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T06:22:28.836+0000] {standard_task_runner.py:63} INFO - Started process 2033 to run task
[2024-05-10T06:22:28.836+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX_v1', 'Enviar_Mensaje', 'scheduled__2024-03-22T00:00:00+00:00', '--job-id', '1280', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX_v1.py', '--cfg-path', '/tmp/tmpr9zqlcez']
[2024-05-10T06:22:28.840+0000] {standard_task_runner.py:91} INFO - Job 1280: Subtask Enviar_Mensaje
[2024-05-10T06:22:28.883+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-22T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T06:22:28.949+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX_v1' AIRFLOW_CTX_TASK_ID='Enviar_Mensaje' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-22T00:00:00+00:00'
[2024-05-10T06:22:28.950+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T06:22:28.959+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-10T06:22:28.960+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo '2024-03-22: Los datos fueron cargados'"]
[2024-05-10T06:22:28.970+0000] {subprocess.py:86} INFO - Output:
[2024-05-10T06:22:29.009+0000] {subprocess.py:93} INFO - 2024-03-22: Los datos fueron cargados
[2024-05-10T06:22:29.012+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-10T06:22:29.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T06:22:29.081+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Proyecto_SpaceX_v1, task_id=Enviar_Mensaje, run_id=scheduled__2024-03-22T00:00:00+00:00, execution_date=20240322T000000, start_date=20240510T062228, end_date=20240510T062229
[2024-05-10T06:22:29.134+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T06:22:29.156+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T06:22:29.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
