[2024-05-10T06:24:34.815+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T06:24:34.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-05-10T06:24:34.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-05-10T06:24:34.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-10T06:24:35.001+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Enviar_Mensaje> on 2024-03-26 00:00:00+00:00
[2024-05-10T06:24:35.009+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T06:24:35.010+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX_v1', 'Enviar_Mensaje', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '1308', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX_v1.py', '--cfg-path', '/tmp/tmpx9tyz3w0']
[2024-05-10T06:24:35.018+0000] {standard_task_runner.py:63} INFO - Started process 2174 to run task
[2024-05-10T06:24:35.019+0000] {standard_task_runner.py:91} INFO - Job 1308: Subtask Enviar_Mensaje
[2024-05-10T06:24:35.081+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX_v1.Enviar_Mensaje scheduled__2024-03-26T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T06:24:35.179+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX_v1' AIRFLOW_CTX_TASK_ID='Enviar_Mensaje' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-05-10T06:24:35.180+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T06:24:35.190+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-10T06:24:35.198+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo '2024-03-26: Los datos fueron cargados'"]
[2024-05-10T06:24:35.208+0000] {subprocess.py:86} INFO - Output:
[2024-05-10T06:24:35.210+0000] {subprocess.py:93} INFO - 2024-03-26: Los datos fueron cargados
[2024-05-10T06:24:35.211+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-10T06:24:35.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T06:24:35.241+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Proyecto_SpaceX_v1, task_id=Enviar_Mensaje, run_id=scheduled__2024-03-26T00:00:00+00:00, execution_date=20240326T000000, start_date=20240510T062434, end_date=20240510T062435
[2024-05-10T06:24:35.315+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T06:24:35.330+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T06:24:35.337+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
