[2024-05-10T06:15:19.789+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T06:15:19.816+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Esperar_archivo scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2024-05-10T06:15:19.831+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Esperar_archivo scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2024-05-10T06:15:19.832+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-10T06:15:19.849+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): Esperar_archivo> on 2024-03-09 00:00:00+00:00
[2024-05-10T06:15:19.855+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1557) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T06:15:19.858+0000] {standard_task_runner.py:63} INFO - Started process 1559 to run task
[2024-05-10T06:15:19.856+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX_v1', 'Esperar_archivo', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '1193', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX_v1.py', '--cfg-path', '/tmp/tmprakukpnl']
[2024-05-10T06:15:19.859+0000] {standard_task_runner.py:91} INFO - Job 1193: Subtask Esperar_archivo
[2024-05-10T06:15:19.909+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX_v1.Esperar_archivo scheduled__2024-03-09T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T06:15:20.115+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX_v1' AIRFLOW_CTX_TASK_ID='Esperar_archivo' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2024-05-10T06:15:20.118+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T06:15:20.131+0000] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-05-10T06:15:20.140+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-05-10T06:15:20.142+0000] {filesystem.py:85} INFO - Poking for file /tmp/platzi_data_20240309.csv
[2024-05-10T06:15:20.144+0000] {filesystem.py:89} INFO - Found File /tmp/platzi_data_20240309.csv last modified: 20240510061518
[2024-05-10T06:15:20.149+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-10T06:15:20.150+0000] {filesystem.py:85} INFO - Poking for file /tmp/platzi_data_20240309.csv
[2024-05-10T06:15:20.153+0000] {filesystem.py:89} INFO - Found File /tmp/platzi_data_20240309.csv last modified: 20240510061518
[2024-05-10T06:15:20.154+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T06:15:20.164+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Proyecto_SpaceX_v1, task_id=Esperar_archivo, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20240510T061519, end_date=20240510T061520
[2024-05-10T06:15:20.193+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T06:15:20.346+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-10T06:15:20.350+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
